# Generated by Django 4.2.23 on 2025-07-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_members_joined_date_members_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="joined_date",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
