# Generated by Django 4.2.23 on 2025-07-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_members_joined_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Members",
            new_name="Member",
        ),
    ]
